### PR TITLE
Fix team review request slack messages

### LINKED ISSUE #210: Review request to group doesn't display group name in status
When I submit review request to a group (ex: console-developers), Octobot doesn't handle the status : `Pull Request submitted for review to  (tanium/tux-console)`

Bonus: Would be nice to display the group name, or even better tag everyone in the group so they get a notification

### PR DESCRIPTION
**Pull request by matthauck**
Fixes #210

### CODE REVIEW

File: octobot/src/server/github_handler.rs [hunk 1]
```diff
@@ -513,6 +513,19 @@ impl GithubEventHandler {
...
     }
 
+    fn reviewer_names(&self, pull_request: &github::PullRequest) -> Vec<String> {
+        let mut reviewer_names = vec![];
+
+        if let Some(ref reviewers) = pull_request.requested_reviewers {
+            reviewer_names.extend(self.slack_user_names(reviewers));
+        }
+        if let Some(ref teams) = pull_request.requested_teams {
+            reviewer_names.extend(teams.into_iter().map(|t| format!("@{}", t.slug)));
```
Comment (matthauck) [inline octobot/src/server/github_handler.rs:523]: looking at GH api responses, looks like `slug` is just the name; does not contain an `@`.

**Review by trevershick — APPROVED** [review]

**Review by ysdanielkim — APPROVED** [review]

**Review by tomemelko — APPROVED** [review]
